//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrapet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrapet.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference path=&quot;intellisense.d.ts&quot; /&gt;
        ///
        ////**
        /// * @param {Namespace} ns 
        /// * @param {Object} self
        /// */
        ///function Events(ns, self) {
        ///    
        ///    self.clicks = [];
        ///    document.addEventListener(&quot;click&quot;, function (ev) {
        ///        let target = ev.originalTarget;
        ///        ns.selection.
        ///            clicks.push({
        ///            });
        ///    });
        ///
        ///    return self; //for intellisense
        ///}.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.__SCRAPET = (function (debug, registry) {
        ///    let private = {
        ///        _maxRegistrationMS: 2000,
        ///        _expected: [...registry],
        ///        _pending: [...registry],
        ///        _registering: [],
        ///        _namespace: { isDebug: debug },
        ///        _destruct: function () {
        ///            this._hide();
        ///            public.Register = null; //remove public Register method
        ///            private = null; //remove private members
        ///        },
        ///        _hide: function () {
        ///            delete window.__SCRAPET; //remo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        /// * @param {Namespace} ns 
        /// * @param  self
        /// * @returns {{AttributeValueSelector:AttributeValueSelector, Attribute:Attribute, AttributeCollection:AttributeCollection }}
        /// */function Selection(ns, self) {
        ///    self.AttributeValueSelector = {
        ///        CONTAINS: &quot;*=&quot;,
        ///        ENDS_WITH: &quot;$=&quot;,
        ///        EQUALS: &quot;=&quot;,
        ///        HYPHEN_EQUALS: &quot;|=&quot;,
        ///        SPACE_CONTAINS: &quot;~=&quot;,
        ///        STARTS_WITH: &quot;^=&quot;,
        ///        contains(value) {
        ///            return value == CONTAINS ||
        ///                value == ENDS_WIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Selections {
            get {
                return ResourceManager.GetString("Selections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    let _eval = window.eval;
        ///    window.eval = function (jsString) {
        ///        if (jsString.indexOf(&quot;\n//# logErrors&quot;) &gt;= 0) {
        ///            try {
        ///                return _eval(jsString);
        ///            }
        ///            catch (ex) {
        ///                console.error(ex);
        ///            }
        ///        }
        ///        else {
        ///            return _eval(jsString);
        ///        }
        ///    };
        ///})();.
        /// </summary>
        internal static string Shim {
            get {
                return ResourceManager.GetString("Shim", resourceCulture);
            }
        }
    }
}
